/* Use this file to export your markdoc tags */
export * from './callout.markdoc';
export * from './table.markdoc';
export * from './image.markdoc';
export * from './home.markdoc';
export * from './gettingstarted.markdocs';
export * from './intro.markdoc';
export * from './environment.markdoc';
export * from './testcredentials.markdocs';
export * from './errors.markdoc';
export * from './apikeys.markdoc';
export * from './integratingklumpview.markdoc';
export * from './integratingklumpgettingstarted.markdown';
export * from './producttesting.markdoc';
export * from './paymentpages.markdoc';
export * from './verification.markdoc';
export * from './transactionverification.markdoc';
export * from './webhook.markdoc';
export * from './webhookgettingstarted.markdoc';
export * from './settingupwebhooks.markdoc';
export * from './resendwebhooks.markdoc';
export * from './plugins.markdoc';
export * from './commerce.markdoc';
export * from './inventorymanagemnt.markdoc'
